language: generic

compiler:
  - gcc
  - clang

sudo: required

matrix:
  include:
    # centos7
    - os: osx
      osx_image: xcode7.3
      env:
        - OS=osx ICEVER=3.6 OMEROVER=latest WEBPORT=8080 WEBPREFIX=/omero

before_install:
  - python --version
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh