---

- hosts: all
  tasks:
    - name: Clean doc
      file:
        path: "{{playbook_dir}}/doc/omeroweb-install-{{ prefix }}.txt"
        state: absent
      when: clean
    - name: Create doc dir
      file:
        path: "{{playbook_dir}}/doc"
        state: directory
        mode: 0755
    - name: Generate omeroweb-install-{{ prefix }}.txt
      template:
        src: "omeroweb-install-doc.txt.j2"
        dest: "{{playbook_dir}}/doc/omeroweb-install-{{ prefix }}.txt"

  vars:
    - doc: True
    - prefix: "{{ os }}-ice{{ ice_version }}"