---

- hosts: all
  tasks:
    - name: Clean doc
      file:
        path: "{{ path }}/doc/omeroweb-install-{{ prefix }}.rst"
        state: absent
      when: clean
    - name: Create doc dir
      file:
        path: "{{ path }}/doc"
        state: directory
        mode: 0755
    - name: Generate omeroweb-install-{{ prefix }}.rst
      template:
        src: "omeroweb-install-doc.txt.j2"
        dest: "{{ path }}/doc/omeroweb-install-{{ prefix }}.rst"

  vars:
    - doc: True
    - prefix: "{{ os }}-ice{{ ice_version }}"