---
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos7, centos8, ubuntu1804, ubuntu2004, debian9, debian10]
        websession: [true, false]
        webprefix: ["", "/omero"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up
        run: ./.travis/before_install.sh
        env:
          OS: ${{ matrix.os }}
          ICEVER: 3.6
          DOCKER: true
          WEBSESSION: ${{ matrix.websession }}
          WEBPREFIX: ${{ matrix.webprefix }}
          TRAVIS_OS_NAME: linux
          TRAVIS: true
      - name: Install
        run: ./.travis/install.sh
        env:
          OS: ${{ matrix.os }}
          ICEVER: 3.6
          DOCKER: true
          WEBSESSION: ${{ matrix.websession }}
          WEBPREFIX: ${{ matrix.webprefix }}
          TRAVIS_OS_NAME: linux
      - name: Script
        run: ./.travis/script.sh
        env:
          TRAVIS_OS_NAME: linux
          OS: ${{ matrix.os }}
  docs:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set branch name
        run: |
          echo "branch_name="${{github.sha}}${GITHUB_REF##*/} >> $GITHUB_ENV
          echo "original_branch_name="${GITHUB_REF##*/} >> $GITHUB_ENV
      - name: Create doc branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.branch_name }}
      - name: Build doc
        run: |
          os=("centos7" "centos8" "debian9" "debian10" "ubuntu2004" "ubuntu1804")
          for i in "${os[@]}"
          do
            ansible-playbook ./ansible/omeroweb-install-doc.yml -i ./ansible/hosts/$i-ice3.6 --extra-vars '{"clean": True, "web_session": True}'
          done
      - name: Commit and push changes to the newly created branch
        run: |
          mv ansible/doc/*.rst docs
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin ${{ env.branch_name }}
          git checkout ${{ env.branch_name }}
          git add -f docs/omeroweb-install-*
          git commit -m 'Update from CI'
      - name: Open Pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update doc
          committer: GitHub <noreply@github.com>
          branch: ${{ env.branch_name }}
          title: 'Update doc'
          base: master
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          body: |
            - corresponding doc changes from [${{ env.original_branch_name }}][1]
            [1]: https://github.com/${{ github.repository }}/tree/${{ env.original_branch_name }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
